version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9093:9093"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
